# Generated by Django 3.1.5 on 2021-01-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('teamName', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='images')),
                ('manager', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('discord', models.CharField(max_length=50)),
                ('player1_name', models.CharField(blank=True, max_length=50)),
                ('player1_email', models.CharField(blank=True, max_length=50)),
                ('player1_contact', models.CharField(blank=True, max_length=50)),
                ('player1_IGN', models.CharField(blank=True, max_length=50)),
                ('player1_UID', models.CharField(blank=True, max_length=50)),
                ('player1_photo', models.ImageField(blank=True, upload_to='images')),
                ('player2_name', models.CharField(blank=True, max_length=50)),
                ('player2_email', models.CharField(blank=True, max_length=50)),
                ('player2_contact', models.CharField(blank=True, max_length=50)),
                ('player2_IGN', models.CharField(blank=True, max_length=50)),
                ('player2_UID', models.CharField(blank=True, max_length=50)),
                ('player2_photo', models.ImageField(blank=True, upload_to='images')),
                ('player3_name', models.CharField(blank=True, max_length=50)),
                ('player3_email', models.CharField(blank=True, max_length=50)),
                ('player3_contact', models.CharField(blank=True, max_length=50)),
                ('player3_IGN', models.CharField(blank=True, max_length=50)),
                ('player3_UID', models.CharField(blank=True, max_length=50)),
                ('player3_photo', models.ImageField(blank=True, upload_to='images')),
                ('player4_name', models.CharField(blank=True, max_length=50)),
                ('player4_email', models.CharField(blank=True, max_length=50)),
                ('player4_contact', models.CharField(blank=True, max_length=50)),
                ('player4_IGN', models.CharField(blank=True, max_length=50)),
                ('player4_UID', models.CharField(blank=True, max_length=50)),
                ('player4_photo', models.ImageField(blank=True, upload_to='images')),
                ('player5_name', models.CharField(blank=True, max_length=50)),
                ('player5_email', models.CharField(blank=True, max_length=50)),
                ('player5_contact', models.CharField(blank=True, max_length=50)),
                ('player5_IGN', models.CharField(blank=True, max_length=50)),
                ('player5_UID', models.CharField(blank=True, max_length=50)),
                ('player5_photo', models.ImageField(blank=True, upload_to='images')),
                ('player6_name', models.CharField(blank=True, max_length=50)),
                ('player6_email', models.CharField(blank=True, max_length=50)),
                ('player6_contact', models.CharField(blank=True, max_length=50)),
                ('player6_IGN', models.CharField(blank=True, max_length=50)),
                ('player6_UID', models.CharField(blank=True, max_length=50)),
                ('player6_photo', models.ImageField(blank=True, upload_to='images')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Free Fire Reg',
            },
        ),
    ]
