# Generated by Django 3.1.4 on 2021-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210107_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('inGameName', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'Free Fire Player',
            },
        ),
        migrations.RenameField(
            model_name='freefire',
            old_name='inGameName',
            new_name='discord',
        ),
        migrations.RenameField(
            model_name='freefire',
            old_name='uid',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='freefire',
            name='username',
        ),
        migrations.AddField(
            model_name='freefire',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='freefire',
            name='players',
            field=models.ManyToManyField(blank=True, to='App.PlayerFF'),
        ),
    ]
