# Generated by Django 3.1.5 on 2021-01-12 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210112_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freefire',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
