# Generated by Django 3.1.5 on 2021-01-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210112_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freefire',
            name='time',
        ),
    ]
