# Generated by Django 3.1.4 on 2021-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210107_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freefire',
            old_name='name',
            new_name='teamName',
        ),
        migrations.RemoveField(
            model_name='freefire',
            name='players',
        ),
        migrations.AddField(
            model_name='freefire',
            name='player1IGN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player1UID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player1contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player1email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player1name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player1photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player2IGN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player2UID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player2contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player2email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player2name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player2photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player3IGN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player3UID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player3contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player3email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player3name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player3photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player4IGN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player4UID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player4contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player4email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player4name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player4photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player5IGN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player5UID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player5contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player5email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player5name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player5photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player6IGN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player6UID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player6contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player6email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player6name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freefire',
            name='player6photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='PlayerFF',
        ),
    ]
