# Generated by Django 3.1.4 on 2021-01-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210107_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freefire',
            old_name='player1name',
            new_name='player1_name',
        ),
    ]
