# Generated by Django 3.1.5 on 2021-01-15 11:05

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_freefire_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freefire',
            name='logo',
            field=models.ImageField(blank=True, upload_to=App.models.get_upload_path),
        ),
    ]
