# Generated by Django 3.1.5 on 2021-01-28 05:04

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210115_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to=App.models.get_upload_path_player)),
                ('manager', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('discord', models.CharField(max_length=50)),
                ('psn', models.CharField(max_length=50)),
                ('ea', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('ign', models.CharField(max_length=50)),
                ('webcam', models.CharField(max_length=50)),
                ('uniqueId', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Fifa Reg',
            },
        ),
        migrations.AlterField(
            model_name='freefire',
            name='player1_photo',
            field=models.ImageField(blank=True, upload_to=App.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='freefire',
            name='player2_photo',
            field=models.ImageField(blank=True, upload_to=App.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='freefire',
            name='player3_photo',
            field=models.ImageField(blank=True, upload_to=App.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='freefire',
            name='player4_photo',
            field=models.ImageField(blank=True, upload_to=App.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='freefire',
            name='player5_photo',
            field=models.ImageField(blank=True, upload_to=App.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='freefire',
            name='player6_photo',
            field=models.ImageField(blank=True, upload_to=App.models.get_upload_path),
        ),
    ]
