# Generated by Django 3.1.5 on 2021-01-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210128_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fifa',
            name='manager',
        ),
    ]
