# Generated by Django 3.1.5 on 2021-02-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_freefire2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freefire2',
            options={'verbose_name': 'Free Fire 2 Reg'},
        ),
    ]
