# Generated by Django 3.1.5 on 2021-03-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_valorant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorant',
            old_name='player1_riotID',
            new_name='player1_UID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player2_riotID',
            new_name='player1_discord',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player3_riotID',
            new_name='player2_UID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player4_riotID',
            new_name='player2_discord',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player5_IGN',
            new_name='player3_UID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player5_contact',
            new_name='player3_discord',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player5_email',
            new_name='player4_UID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player5_name',
            new_name='player4_discord',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player5_riotID',
            new_name='player5_UID',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player1_photo',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player2_photo',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player3_photo',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player4_photo',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player5_photo',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player6_contact',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player6_email',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player6_name',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player6_photo',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player6_riotID',
        ),
    ]
