# Generated by Django 3.1.5 on 2021-03-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20210309_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freefire',
            old_name='player1_UID',
            new_name='player1_riotID',
        ),
        migrations.RenameField(
            model_name='freefire',
            old_name='player2_UID',
            new_name='player2_riotID',
        ),
        migrations.RenameField(
            model_name='freefire',
            old_name='player3_UID',
            new_name='player3_riotID',
        ),
        migrations.RenameField(
            model_name='freefire',
            old_name='player4_UID',
            new_name='player4_riotID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player1_UID',
            new_name='player1_riotID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player2_UID',
            new_name='player2_riotID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player3_UID',
            new_name='player3_riotID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player4_UID',
            new_name='player4_riotID',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player5_UID',
            new_name='player5_riotID',
        ),
    ]
