# Generated by Django 3.1.5 on 2021-03-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20210309_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freefire',
            old_name='player1_riotID',
            new_name='player1_UID',
        ),
        migrations.RenameField(
            model_name='freefire',
            old_name='player2_riotID',
            new_name='player2_UID',
        ),
        migrations.RenameField(
            model_name='freefire',
            old_name='player3_riotID',
            new_name='player3_UID',
        ),
        migrations.RenameField(
            model_name='freefire',
            old_name='player4_riotID',
            new_name='player4_UID',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player6_IGN',
        ),
    ]
