# Generated by Django 3.1.5 on 2021-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20210309_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorant',
            name='player6_riotID',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
