# Generated by Django 3.1.5 on 2021-03-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_valorant_player6_riotid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorant',
            old_name='player5_riotID',
            new_name='player5_IGN',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player6_riotID',
            new_name='player6_IGN',
        ),
    ]
