# Generated by Django 3.1.5 on 2021-03-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20210309_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorant',
            name='manager',
        ),
    ]
