# Generated by Django 3.1.5 on 2021-03-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_valorant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorant',
            name='player5_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='valorant',
            name='player5_discord',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='valorant',
            name='player5_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='valorant',
            name='player5_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='valorant',
            name='player5_riotID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='valorant',
            name='player7_IGN',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
