# Generated by Django 3.1.5 on 2021-03-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20210322_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorant',
            name='player1_IGN',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player2_IGN',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player3_IGN',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player4_IGN',
        ),
        migrations.RemoveField(
            model_name='valorant',
            name='player5_IGN',
        ),
    ]
