# Generated by Django 3.1.5 on 2021-03-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20210325_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorant',
            old_name='player1_riotID',
            new_name='player1_IGN',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player2_riotID',
            new_name='player2_IGN',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player3_riotID',
            new_name='player3_IGN',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player4_riotID',
            new_name='player4_IGN',
        ),
        migrations.RenameField(
            model_name='valorant',
            old_name='player5_riotID',
            new_name='player5_IGN',
        ),
    ]
