# Generated by Django 3.2.1 on 2021-05-19 11:01

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_auto_20210413_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='valorant3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('teamName', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to=App.models.get_upload_path_valo2)),
                ('contact', models.CharField(max_length=50)),
                ('player1_name', models.CharField(blank=True, max_length=50)),
                ('player1_email', models.CharField(blank=True, max_length=50)),
                ('player1_contact', models.CharField(blank=True, max_length=50)),
                ('player1_IGN', models.CharField(blank=True, max_length=50)),
                ('player1_discord', models.CharField(blank=True, max_length=50)),
                ('player2_name', models.CharField(blank=True, max_length=50)),
                ('player2_email', models.CharField(blank=True, max_length=50)),
                ('player2_contact', models.CharField(blank=True, max_length=50)),
                ('player2_IGN', models.CharField(blank=True, max_length=50)),
                ('player2_discord', models.CharField(blank=True, max_length=50)),
                ('player3_name', models.CharField(blank=True, max_length=50)),
                ('player3_email', models.CharField(blank=True, max_length=50)),
                ('player3_contact', models.CharField(blank=True, max_length=50)),
                ('player3_IGN', models.CharField(blank=True, max_length=50)),
                ('player3_discord', models.CharField(blank=True, max_length=50)),
                ('player4_name', models.CharField(blank=True, max_length=50)),
                ('player4_email', models.CharField(blank=True, max_length=50)),
                ('player4_contact', models.CharField(blank=True, max_length=50)),
                ('player4_IGN', models.CharField(blank=True, max_length=50)),
                ('player4_discord', models.CharField(blank=True, max_length=50)),
                ('player5_name', models.CharField(blank=True, max_length=50)),
                ('player5_email', models.CharField(blank=True, max_length=50)),
                ('player5_contact', models.CharField(blank=True, max_length=50)),
                ('player5_IGN', models.CharField(blank=True, max_length=50)),
                ('player5_discord', models.CharField(blank=True, max_length=50)),
                ('player6_IGN', models.CharField(blank=True, max_length=50)),
                ('player7_IGN', models.CharField(blank=True, max_length=50)),
                ('uniqueId', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Valorant 2 Reg',
            },
        ),
    ]
