# Generated by Django 3.2.1 on 2021-05-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_valorant3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorant3',
            options={'verbose_name': 'Valorant 3 Reg'},
        ),
    ]
