# Generated by Django 3.2.1 on 2021-07-20 11:48

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_valorant4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fifa2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to=App.models.get_upload_path_player)),
                ('contact', models.CharField(max_length=50)),
                ('discord', models.CharField(max_length=50)),
                ('psn', models.CharField(max_length=50)),
                ('ea', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('ign', models.CharField(max_length=50)),
                ('webcam', models.CharField(max_length=50)),
                ('uniqueId', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Fifa Reg',
            },
        ),
    ]
