# Generated by Django 3.2.1 on 2021-07-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_fifa2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fifa2',
            options={'verbose_name': 'Fifa 2 Reg'},
        ),
    ]
