# Generated by Django 3.2.1 on 2021-08-19 01:57

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_fifa2_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFire3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('teamName', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to=App.models.get_upload_path)),
                ('manager', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('discord', models.CharField(max_length=50)),
                ('player1_name', models.CharField(blank=True, max_length=50)),
                ('player1_email', models.CharField(blank=True, max_length=50)),
                ('player1_contact', models.CharField(blank=True, max_length=50)),
                ('player1_IGN', models.CharField(blank=True, max_length=50)),
                ('player1_UID', models.CharField(blank=True, max_length=50)),
                ('player1_photo', models.ImageField(blank=True, upload_to=App.models.get_upload_path)),
                ('player2_name', models.CharField(blank=True, max_length=50)),
                ('player2_email', models.CharField(blank=True, max_length=50)),
                ('player2_contact', models.CharField(blank=True, max_length=50)),
                ('player2_IGN', models.CharField(blank=True, max_length=50)),
                ('player2_UID', models.CharField(blank=True, max_length=50)),
                ('player2_photo', models.ImageField(blank=True, upload_to=App.models.get_upload_path)),
                ('player3_name', models.CharField(blank=True, max_length=50)),
                ('player3_email', models.CharField(blank=True, max_length=50)),
                ('player3_contact', models.CharField(blank=True, max_length=50)),
                ('player3_IGN', models.CharField(blank=True, max_length=50)),
                ('player3_UID', models.CharField(blank=True, max_length=50)),
                ('player3_photo', models.ImageField(blank=True, upload_to=App.models.get_upload_path)),
                ('player4_name', models.CharField(blank=True, max_length=50)),
                ('player4_email', models.CharField(blank=True, max_length=50)),
                ('player4_contact', models.CharField(blank=True, max_length=50)),
                ('player4_IGN', models.CharField(blank=True, max_length=50)),
                ('player4_UID', models.CharField(blank=True, max_length=50)),
                ('player4_photo', models.ImageField(blank=True, upload_to=App.models.get_upload_path)),
                ('player5_name', models.CharField(blank=True, max_length=50)),
                ('player5_email', models.CharField(blank=True, max_length=50)),
                ('player5_contact', models.CharField(blank=True, max_length=50)),
                ('player5_IGN', models.CharField(blank=True, max_length=50)),
                ('player5_UID', models.CharField(blank=True, max_length=50)),
                ('player5_photo', models.ImageField(blank=True, upload_to=App.models.get_upload_path)),
                ('player6_name', models.CharField(blank=True, max_length=50)),
                ('player6_email', models.CharField(blank=True, max_length=50)),
                ('player6_contact', models.CharField(blank=True, max_length=50)),
                ('player6_IGN', models.CharField(blank=True, max_length=50)),
                ('player6_UID', models.CharField(blank=True, max_length=50)),
                ('player6_photo', models.ImageField(blank=True, upload_to=App.models.get_upload_path)),
                ('uniqueId', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Free Fire Reg 3',
            },
        ),
    ]
