# Generated by Django 3.2.1 on 2021-09-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_auto_20210918_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freefire4',
            options={'verbose_name': 'Free Fire 4 Reg'},
        ),
    ]
